@startuml
'https://plantuml.com/sequence-diagram

participant クライアント
participant サーバー
participant DB

autonumber

rnote over クライアント,DB:ログイン画面

alt アカウント作成時

クライアント -> サーバー:新規ユーザーID\nパスワード
rnote over サーバー:入力内容チェック
サーバー -> DB:ユーザーID\nパスワード
rnote over サーバー:登録できたかチェック
サーバー <- DB:プレイデータ
サーバー -> クライアント:タイトル移行フラグ\nプレイデータ

end

alt ログイン時

クライアント -> サーバー:ユーザーID\nパスワード
rnote over サーバー:入力内容チェック
サーバー -> DB:ユーザーID\nパスワード
サーバー <- DB:プレイデータ
サーバー -> クライアント:タイトル移行フラグ\nプレイデータ

end

rnote over クライアント,DB:タイトル画面

rnote over クライアント:プレイデータから\n対応した選択画面を表示

alt はじめからを選択

クライアント -> サーバー:選択フラグ
サーバー -> DB:プレイデータ初期化
サーバー <- DB:初期化データを取得
クライアント <- サーバー:データを取得\nゲーム画面移行

end

alt つづきからを選択

クライアント -> サーバー:選択フラグ
クライアント <- サーバー:ゲーム画面移行

end

alt しゅうりょうを選択

クライアント -> サーバー:選択フラグ
クライアント <- サーバー:ゲーム終了フラグ
rnote over クライアント:終了処理

end

rnote over クライアント,DB:ゲーム画面

loop 終了か切断するまで



end

@enduml